### ISSUE TITLE
Переработка evo-tabs

### ISSUE THREAD

**Issue by NorthFailer** [evotor/Evo-UI-Kit#154]
# 🚀 feature request

### Description

На данный момент в табах есть следующие проблемы:

1) Отступы между табами не кликабельны
2) evo-tab-item не работает с *ngFor

Какие вещи хотелось чтобы работали(не проверено на текущей реализации):

1) Табы визуализировали и переключали hash в URL
2) Поддержка нескольких hash одновременно на странице(нужен формат мультихеша)
3) Добавить возможность скролла страницы до табов(т.е. реализовать метки к которым можно скроллить внешним кодом)
4) Помечать контент таба через hash в шаблоне
5) Адаптив(перенос в 2 ряда? скролл?)
6) Исправить проблемы описанные выше.

Все это также требует пересмотра дизайна элемента, Мартынов в курсе нескольких проблем.

### Describe the solution you'd like
Предлагаю полностью переделать табы.

Usage:
Evo-Ui - 0
Evo-Dashboard - 1
Evo-Dev - 0(там локальная реализация)

### Describe alternatives you've considered
Как альтернатива попробовать сохранить текущий формат структуры, но не исключено, что так и будет, если это возможно

**Comment by rsboarder** [comment]
У нас есть http://ui-kit.market.local/?path=/story/components-submenu--default и мне кажется, что эти два компонента надо объединить.

**Comment by NorthFailer** [comment]
@rsboarder так у этих компонентов совсем разное поведение, submenu sticky + само переключается при скролле страницы к определенному id/hash, а табы просто переключают контент на странице.
Не будет ли это оверинженеринг объединять их в одно?

**Comment by andreymatveev** [comment]
Я бы предложил сделать следующее:

1. вынести фичу с прилипанием в отдельную директиву
2. создать компонент счётчика 
![image](https://user-images.githubusercontent.com/712101/60021603-7efc6900-96bc-11e9-9fa1-0f139f38c060.png) (используется в нескольких местах)
3. добавить в сабменю возможность работы со счётчиком (нужно и для табов)
4. сделать табы на основе сабменю

**Comment by rsboarder** [comment]
> 1. вынести фичу с прилипанием в отдельную директиву

для этой "фичи" есть `position: sticky` и этим можно управлять снаружи компонента(в теории).

**Comment by andreymatveev** [comment]
> для этой "фичи" есть position: sticky и этим можно управлять снаружи компонента(в теории).

Да, но 
1. нужна определённая вёрстка контейнера под это
2. для ИЕ всё равно придётся делать фолбэк

**Comment by rsboarder** [comment]
> 2\. для ИЕ всё равно придётся делать фолбэк

точно! забыл про него :(

**Comment by ElenaMazyrina** [comment]
> @rsboarder так у этих компонентов совсем разное поведение, submenu sticky + само переключается при скролле страницы к определенному id/hash, а табы просто переключают контент на странице.
> Не будет ли это оверинженеринг объединять их в одно?

просто выскажу свое скромное мнение, но мне тоже кажется, что у них разный функционал. И они могли бы отдельно жить ^__^

**Comment by NorthFailer** [comment]
@andreymatveev Идея с прилипанием мне нравится, но как быть если стиль прилепливаемого элемента нужно изменить?
По поводу счетчика, можно сделать отдельный компонент, но причем тут табы? Имеется в виду что в контент таба надо чтобы html можно было поместить а не только строки?

**Comment by rsboarder** [comment]
> просто выскажу свое скромное мнение, но мне тоже кажется, что у них разный функционал. И они могли бы отдельно жить ^__^

почему тебе так кажется?

**Comment by andreymatveev** [comment]
> как быть если стиль прилепливаемого элемента нужно изменить?

Не совсем понимаю, где тут может быть проблема. Можно вообще попробовать что-нибудь готовенькое, вроде https://github.com/w11k/angular-sticky-things )

> По поводу счетчика, можно сделать отдельный компонент, но причем тут табы

Это, скорее, для того, чтобы не забыть запилить эту фичу отдельно. 

> но мне тоже кажется, что у них разный функционал
> так у этих компонентов совсем разное поведение

Я, кажется понял, о чём вы. С помощью сабменю можно реализовать табы, которые *зависят* от роута, а вы с Леной, скорее, о тех, которые *не трогают урлы*. 

В таком случае, действительно, придётся разделять эти компоненты. 

Как вариант, можно заморочиться и запилить:
1. компонент для пункта меню `evo-menu-link`
2. компонент для панели из пунктов меню `evo-menu-bar` (по сути, контейнер для `evo-menu-link`, тянется по ширине родителя)
3. компоненты для табов `evo-tabs` сделать на базе предыдущих двух
4. с сабменю надо подумать, нужно ли оно)

**Comment by thekip** [comment]
> Не совсем понимаю, где тут может быть проблема. Можно вообще попробовать что-нибудь готовенькое, вроде https://github.com/w11k/angular-sticky-things )

Вставлю свои пять копеек. Лучше заюзать position: sticky, и если так надо для ИЕ, либо graceful degradation (просто не стикать) либо полифилл. И заканчивать использовать "готовенькое" - просто мусорный код, из которого в реальном приложении будет использовано от силы 10%, все остальное кейсы "на все случаи жизни и на всякий случай"

**Comment by andreymatveev** [comment]
> если так надо для ИЕ
Надо. Я повторюсь: я не против стики, но нужно будет пересмотреть вёрстку на основных проектах. 

> заканчивать использовать "готовенькое"
Да мы не начинали особо, это просто был пример, как можно делать. 

С прилипанием предлагаю в соответствующем треде разбираться.

**Comment by NorthFailer** [comment]
> Я, кажется понял, о чём вы. С помощью сабменю можно реализовать табы, которые _зависят_ от роута, а вы с Леной, скорее, о тех, которые _не трогают урлы_.
> 
> В таком случае, действительно, придётся разделять эти компоненты.

@andreymatveev не понимаю почему ты решил что табы не будут менять hash у URL? Это описано в самом первом посте.

**Comment by NorthFailer** [comment]
разница в том что sub-menu следит за body scroll, а табы за активным контентом

**Comment by andreymatveev** [comment]
> разница в том что sub-menu следит за body scroll, а табы за активным контентом

Сабменю на данный момент имеет несколько типов действия пунктов  https://github.com/evotor/Evo-UI-Kit/blob/master/projects/evo-ui-kit/src/lib/components/evo-submenu/evo-submenu.component.ts#L12

И следит за скроллом только в случае типа `scroll`
https://github.com/evotor/Evo-UI-Kit/blob/master/projects/evo-ui-kit/src/lib/components/evo-submenu/evo-submenu.component.ts#L85

> Это описано в самом первом посте.

Сорян, проглядел. Но в целом, мне кажется, возможен вариант «лёгких табов» без изменения роутов.

**Comment by NorthFailer** [comment]
Ребят, итог обсуждения надо подвести, мне он не очевиден. В ближайшие дни собираюсь этим заняться

**Comment by NorthFailer** [comment]
Итоги обсуждения:

1) Модернизируем компонент evo-tabs.
2) Учитываем проблемы описанные вверху.
3) Оставляем tab-item. 1 таб - 1 компонент
4) Табы не взаимодействуют с навигацией
5) Контент таба идет отдельно от таба
6) Уточнить об адаптиве
7) Counter идет отдельным миксином/классом (см. класс на корзине .amount)
