### ISSUE TITLE
evo-modal: доработки 

### ISSUE THREAD

**Issue by andreymatveev** [evotor/Evo-UI-Kit#183]
### Дизайн
[Фигма](https://www.figma.com/file/TJMwN4a8wGEvVYTKQpUAbgC0/Evotor-UI-Kit?node-id=3552%3A261) (два листа)

#### 1. Поддержка асинхронного accept-действия

Сейчас окно закрывается по нажатию на decline или accept, и нет возможности показать процесс (например, запрос). Не думаю, что на decline тоже нужно вешать такую возможность, поэтому пока предлагаю добавить опциональный параметр:
```
@Input() asyncAccept: Observable<any>;
```
При нажатии на accept будет создаваться подписка на asyncAccept, кнопка accept будет в состоянии лоадера, а кнопка decline — заблокирована. По завершению подписки, модалка закрывается, кнопки разблокируются и тд. 

#### 2. Правки дизайна
- Отступы
- Мобильный вид (нужно уточнить у дизайнеров про отступы от границ экрана)

#### 3. Убрать EvoModalTypes
Сейчас это не используется в компоненте. В дизайне на данный момент фиксированная ширина модалки (для мобилы и для не мобилы). 

#### 4. Плавное появление и исчезание окна
Пока реализовать подобно [бутстраповскому эффекту](https://getbootstrap.com/docs/4.0/components/modal/#live-demo)

#### 5. Закрытие окна по клавише ESC
Я вижу два варианта:
- Задавать это булевым параметром (аналогично бутстраповскому параметру `keyboard`)
- Включать это по умолчанию для вариантов, когда задан `declineText` (то есть, если есть кнопка отмены, то по ESC всегда закрывается)

Название атрибута для варианта 1:
```
@Input() closeOnEsc: boolean = false;
```

#### 6. (под вопросом) Задание заголовка окна через параметр компонента
Сейчас контент модалки полностью задаётся через контент блока: иконка, заголовок, текст — всё, кроме кнопок действий. Можно зафиксировать дизайн заголовка, чтобы не описывать его каждый раз. 

```
@Input() titleText: string = '';
```

#### 7. (под вопросом) Задание иконки модалки через параметр компонента
Аналогичная п. 6 ситуация. Можно задавать параметром шейп иконки и цвет заливки. Размер, судя по дизайну, фиксирован, поэтому не вижу смысла добавлять параметр. 

```
@Input() iconShape: string = '';
@Input() iconColor: string = '';
```

По-хорошему, для цвета иконки нужно использовать переменные из SCSS. Поэтому, скорее всего, придётся делать ограничение значений для `iconColor`.

**Comment by NorthFailer** [comment]
1. ✅
2. ✅
3. ✅
4. ✅Не забывай что делая такой эффект тебе надо кидать событие о закрытие модалки, после его физического исчезновения. Это необходимо, чтобы сбрасывать состояния внутри модалки не на глазах у юзера. Советую юзать Angular animations. 
5. ✅Почему бы и нет.
6. ✅Когда делал компонент, были модалки и без заголовков и с кастомными заголовками. Если сейчас есть общий стандарт - то ок.
7. ❌Не очень нравится идея, почти все модалки старые не имели иконок

**Comment by andreymatveev** [comment]
Окей, 7 пункт мне самому не нравится. Но, скорее всего, я воспользуюсь `ng-content select` для отделения иконки и текста модального окна, поскольку по дизайну между ними будет заголовок. 

По сервису — отличная идея с передачей объекта, этого действительно не хватает.

**Comment by rsboarder** [comment]
А почему закрытие по `esc` ты хочешь сделать опциональным?

**Comment by andreymatveev** [comment]
> А почему закрытие по esc ты хочешь сделать опциональным?

Судя по ЛК, бывают модалки без кнопки Отмена. 

Мне кажется, этот кейс лучше сразу предусмотреть. Можно включить по умолчанию закрытие, и тогда эта опция будет практически незаметной.

**Comment by rsboarder** [comment]
Я бы предложил сделать параметр, который отвечает за наличие кнопки Отмена. А `esc` должен работать всегда, если есть отмена.

**Comment by andreymatveev** [comment]
> Я бы предложил сделать параметр, который отвечает за наличие кнопки Отмена. А esc должен работать всегда, если есть отмена.

Да, я об этом и писал в 5 пункте:

> Я вижу два варианта:
> 
> - Задавать это булевым параметром (аналогично бутстраповскому параметру keyboard)
> - Включать это по умолчанию для вариантов, когда задан declineText (то есть, если есть кнопка отмены, то по ESC всегда закрывается)

Окей, мне вариант 2 тоже нравится.

**Comment by andreymatveev** [comment]
https://github.com/evotor/Evo-UI-Kit/pull/186
