### ISSUE TITLE
Добавить поведение для EvoToast

### ISSUE THREAD

**Issue by Komock** [evotor/Evo-UI-Kit#187]
Считаю стоит добавит в EvoToast свойство `skipQueue?: boolean;` при котором тосты не встают в очередь по 5 секунд, а при появлении нового чистится очередь и показывается последний.

Иногда новый тост приходит раньше с более релевантной  информацией и его хочется отобразить сразу. Это дефолтная механика работы [snack-bar](https://material.angular.io/components/snack-bar/overview) в Angular Material

PS: Или добавить свойство `mode: 'queue' | 'race' | 'permanent'` которое будет задавать поведение для тоста? 🤔

**Comment by rsboarder** [comment]
Либо добавить метод `flush` в `EvoToastService`, который будет явно убирать все сообщения. Всё-таки свойства и режим в данной ситуации мне кажутся неявными.

**Comment by Komock** [comment]
@rsboarder Тогда прийдется каждый раз по 2 метода вызывать вместо 1 и не факт что чистка очереди нужна будет явно так как у нас нет доступа к очереди и мы не знаем есть ли в ней что-то

**Comment by NorthFailer** [comment]
https://github.com/evotor/Evo-UI-Kit/pull/193
